theme: jekyll-theme-minimal
title: AI Agent Recipes
description: Examples of workable instructions to constrain your agent to modern software engineering practices.

# GitHub Pages settings
url: "https://uvayankee.github.io"
baseurl: ""

# Include directories
include:
  - _pages

# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  pages:
    output: true
    permalink: /:basename/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
